# Generated by Django 5.0.3 on 2024-06-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio_sesion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='NIT',
            field=models.CharField(max_length=100),
        ),
    ]
