# Generated by Django 5.0.3 on 2024-06-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadosEmpresa',
            fields=[
                ('id_resultado_emp', models.AutoField(primary_key=True, serialize=False)),
                ('id_empresa', models.IntegerField()),
                ('id_formulario_nombre', models.IntegerField()),
                ('evaluado_empre', models.IntegerField()),
                ('resultado_empre', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultadosUsuario',
            fields=[
                ('id_resultado_usu', models.AutoField(primary_key=True, serialize=False)),
                ('id_empleado', models.IntegerField()),
                ('id_empresa_empleado', models.IntegerField()),
                ('id_formulario', models.IntegerField()),
                ('evaluado_usu', models.IntegerField()),
                ('resultado_usu', models.FloatField()),
            ],
        ),
    ]
